import json
import pandas as pd
from datetime import datetime

def export_execution_plan_json(execution_plan: dict) -> str:
    """
    Exports comprehensive execution plan as a formatted, transparent JSON string for audit.
    Includes query details, intent engine used, tool selection & skip rationale, and optimization metrics.
    """
    enriched_plan = {
        "audit_metadata": {
            "timestamp": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            "platform": "SentinelAML Institutional Platform",
            "version": "2.0.0"
        },
        "query_analysis": {
            "detected_intent": execution_plan.get("detected_intent"),
            "extracted_filters": execution_plan.get("extracted_filters"),
            "planner_reasoning": execution_plan.get("reason_for_plan")
        },
        "tool_selection_audit": {
            "selected_tools": execution_plan.get("selected_tools", []),
            "selected_tool_reasons": execution_plan.get("selected_tool_reasons", {}),
            "skipped_tools": execution_plan.get("skipped_tools", []),
            "skipped_tool_reasons": execution_plan.get("skipped_tool_reasons", {})
        },
        "optimization_metrics": execution_plan.get("optimization_metrics", {})
    }
    return json.dumps(enriched_plan, indent=2)

def generate_html_customer_report(cust_dict: dict) -> str:
    """
    Generates downloadable HTML compliance report for a specific customer.
    """
    cust_id = cust_dict.get("customer_id", "UNKNOWN")
    segment = cust_dict.get("segment", "Retail")
    risk_score = cust_dict.get("risk_score", 0.0)
    risk_level = cust_dict.get("risk_level", "Low")
    patterns = cust_dict.get("triggered_patterns", "None")
    short_exp = cust_dict.get("short_explanation", "")
    detailed_exp = cust_dict.get("detailed_explanation", "")
    action = cust_dict.get("recommended_action", "Monitor")
    urgency = cust_dict.get("urgency_level", "Low")
    rationale = cust_dict.get("action_rationale", "")
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>SentinelAML Compliance Report - Account {cust_id}</title>
    <style>
        body {{ font-family: 'Inter', -apple-system, sans-serif; line-height: 1.6; color: #0F172A; margin: 40px; background-color: #F8FAFC; }}
        .header {{ background-color: #0F172A; color: #ffffff; padding: 24px; border-radius: 8px; margin-bottom: 24px; }}
        .header h1 {{ margin: 0; font-size: 22px; }}
        .header p {{ margin: 4px 0 0 0; color: #94A3B8; font-size: 13px; }}
        .card {{ background: #ffffff; padding: 20px; border-radius: 8px; border: 1px solid #E2E8F0; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.03); }}
        .badge-High {{ background-color: #FEE2E2; color: #991B1B; padding: 4px 12px; border-radius: 4px; font-weight: bold; }}
        .badge-Medium {{ background-color: #FEF3C7; color: #92400E; padding: 4px 12px; border-radius: 4px; font-weight: bold; }}
        .badge-Low {{ background-color: #D1FAE5; color: #065F46; padding: 4px 12px; border-radius: 4px; font-weight: bold; }}
        .label {{ font-weight: bold; color: #475569; }}
        ul {{ padding-left: 20px; }}
        .footer {{ font-size: 12px; color: #64748B; margin-top: 40px; text-align: center; border-top: 1px solid #E2E8F0; padding-top: 15px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>SentinelAML Institutional Case Report</h1>
        <p>Target Account: {cust_id} ({segment} Segment) | Generated by SentinelAML Agent</p>
    </div>

    <div class="card">
        <h2>Risk Assessment Summary</h2>
        <p><span class="label">Account ID:</span> {cust_id}</p>
        <p><span class="label">Customer Segment:</span> {segment}</p>
        <p><span class="label">Risk Score:</span> {risk_score:.1f} / 100</p>
        <p><span class="label">Risk Tier:</span> <span class="badge-{risk_level}">{risk_level}</span></p>
        <p><span class="label">Triggered Indicators:</span> {patterns}</p>
    </div>

    <div class="card">
        <h2>Empirical Evidence & Explanation</h2>
        <p><strong>Executive Summary:</strong></p>
        <p>{short_exp}</p>
        <p><strong>Detailed Findings:</strong></p>
        <pre style="background: #F8FAFC; padding: 15px; border-radius: 4px; white-space: pre-wrap; font-family: monospace;">{detailed_exp}</pre>
    </div>

    <div class="card">
        <h2>Recommended Compliance Action</h2>
        <p><span class="label">Action:</span> <strong>{action}</strong></p>
        <p><span class="label">Priority Urgency:</span> {urgency}</p>
        <p><span class="label">Action Rationale:</span> {rationale}</p>
    </div>

    <div class="footer">
        <p>CONFIDENTIAL INSTITUTIONAL COMPLIANCE DOCUMENT — FOR AUTHORIZED ANALYST USE ONLY</p>
    </div>
</body>
</html>
"""
    return html
